app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{
	Route::resource('server', 'ServerController');
	Route::resource('server.service', 'ServiceController', ['except' => ['index', 'show']]);
	Route::resource('event', 'EventController');
	Route::resource('user', 'UserController');
});

Route::get('/', function() {
	$upcoming_events = \App\Event::upcoming()->get();
	$ongoing_events = \App\Event::ongoing()->get();

	return view('front/index',
		compact(
			'upcoming_events',
			'ongoing_events'
		)
	);
});

Route::resource('event', 'EventController');

app/Event.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use App\Service;
use App\Server;

class Event extends Model
{
	/**
	 * The attributes available for mass assignment.
	 *
	 * @var array
	 **/
	protected $fillable = [
		'bt_start_time',
		'rt_start_time',
		'description',
		'bt_capacity',
		'rt_capacity',
		'start_time',
		'server_id',
		'end_time',
		'name',
	];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 **/
	protected $dates = [
		'bt_start_time',
		'rt_start_time',
		'created_at',
		'updated_at',
		'start_time',
		'end_time',
	];

	/**
	 * An Event belongs to a Server.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function server()
	{
		return $this->belongsTo(Server::class);
	}

	/**
	 * An Event has many Services.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function services()
	{
		return $this->hasMany(Service::class);
	}

	/**
	 * Scope a query to only include upcoming events.
	 *
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public function scopeUpcoming($event)
	{
		return $event->where('start_time', '>', Carbon::now());
	}

	/**
	 * Scope a query to only include ongoing events.
	 *
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public function scopeOngoing($event)
	{
		return $event->where('start_time', '<', Carbon::now())
			->where('end_time', '>', Carbon::now());
	}
}

app/Http/Controllers/Admin/EventController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Server;
use App\Event;

class EventController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$events = Event::with('server')->get();

		return view('admin/event/index', compact('events'));
	}

	/**
	 * Display a template for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$servers = Server::lists('name', 'id');

		return view('admin/event/create', compact('servers'));
	}

	/**
	 * Display a template for editing an existing event.
	 *
	 * @return Response
	 */
	public function edit($event)
	{
		$event = Event::findOrFail($event);
		$servers = Server::lists('name', 'id');

		return view('admin/event/edit',
			compact(
				'servers',
				'event'
			)
		);
	}

	/**
	 * Create a new resource.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$input = $request->input();

		Event::create($input);

		return redirect()->route('admin.event.index');
	}

	/**
	 * Update an existing resource.
	 *
	 * @return Response
	 */
	public function update($event, Request $request)
	{
		$input = $request->input();
		$event = Event::findOrFail($event);

		$event->update($input);

		return redirect()->route('admin.event.index');
	}

	/**
	 * Destroy an existing resource.
	 *
	 * @return Response
	 */
	public function destroy($event)
	{
		Event::destroy($event);

		return redirect()->route('admin.event.index');
	}
}

app/Http/Controllers/EventController.php
<?php namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Event;

class EventController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$events = Event::all();

		return view('front/event/index', compact('events'));
	}

	/**
	 * Display a single resource.
	 *
	 * @return Response
	 */
	public function show($event)
	{
		$event = Event::findOrFail($event);

		return view('front/event/show', compact('event'));
	}
}

resources/views/admin/event/create.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Events</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			{!! Form::open(['route' => 'admin.event.store', 'method' => 'POST']) !!}
				<legend>New Event</legend>
				<div class="form-group">
					{!! Form::label('server_id', 'Server', ['class' => 'control-label']) !!}
					{!! Form::select('server_id', $servers, null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
					{!! Form::text('name', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('description', 'Description', ['class' => 'control-label']) !!}
					{!! Form::textarea('description', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('start_time', 'Start Time', ['class' => 'control-label']) !!}
					{!! Form::text('start_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('end_time', 'End Time', ['class' => 'control-label']) !!}
					{!! Form::text('end_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('bt_start_time', 'Blue Team Start Time', ['class' => 'control-label']) !!}
					{!! Form::text('bt_start_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('rt_start_time', 'Red Team Start Time', ['class' => 'control-label']) !!}
					{!! Form::text('rt_start_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('bt_capacity', 'Blue Team Capacity', ['class' => 'control-label']) !!}
					{!! Form::text('bt_capacity', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('rt_capacity', 'Red Team Capacity', ['class' => 'control-label']) !!}
					{!! Form::text('rt_capacity', null, ['class' => 'form-control']) !!}
				</div>

				{!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
			{!! Form::close() !!}
		</div>
	</div>
@stop

@section('script')
	<script>
	$(document).ready(function() {
		$('.datetimepicker').datetimepicker({

		});
	});
	</script>
@stop

resources/views/admin/event/edit.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Events</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			{!! Form::model($event, ['route' => ['admin.event.update', $event->id], 'method' => 'PUT']) !!}
				<legend>New Event</legend>
				<div class="form-group">
					{!! Form::label('server_id', 'Server', ['class' => 'control-label']) !!}
					{!! Form::select('server_id', $servers, null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
					{!! Form::text('name', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('description', 'Description', ['class' => 'control-label']) !!}
					{!! Form::textarea('description', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('start_time', 'Start Time', ['class' => 'control-label']) !!}
					{!! Form::text('start_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('end_time', 'End Time', ['class' => 'control-label']) !!}
					{!! Form::text('end_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('bt_start_time', 'Blue Team Start Time', ['class' => 'control-label']) !!}
					{!! Form::text('bt_start_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('rt_start_time', 'Red Team Start Time', ['class' => 'control-label']) !!}
					{!! Form::text('rt_start_time', null, ['class' => 'form-control datetimepicker']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('bt_capacity', 'Blue Team Capacity', ['class' => 'control-label']) !!}
					{!! Form::text('bt_capacity', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('rt_capacity', 'Red Team Capacity', ['class' => 'control-label']) !!}
					{!! Form::text('rt_capacity', null, ['class' => 'form-control']) !!}
				</div>

				{!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
			{!! Form::close() !!}
		</div>
	</div>
@stop

@section('script')
	<script>
	$(document).ready(function() {
		$('.datetimepicker').datetimepicker({
			sideBySide: true,
			format: 'YYYY-MM-DD HH:mm:ss'
		});
	});
	</script>
@stop

resources/views/admin/event/index.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>
				Events
				<a href="{{ route('admin.event.create') }}" class="btn btn-success pull-right">New Event</a>
			</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			<table class="table table-striped table-bordered">
				<thead>
					<th>Name</th>
					<th>Server</th>
					<th>Start</th>
					<th>End</th>
					<th>Actions</th>
				</thead>
				<tbody>
					@foreach ($events as $event)
						<tr>
							<td>{{ $event->name }}</td>
							<td>{{ $event->server->name }}</td>
							<td>{{ $event->start_time }}</td>
							<td>{{ $event->end_time }}</td>
							<td>
								<a href="{{ route('admin.event.edit', $event->id) }}" class="btn btn-xs btn-primary">Edit</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@stop