app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{
	Route::resource('server', 'ServerController');
	Route::resource('server.service', 'ServiceController', ['except' => ['index', 'show']]);
	Route::resource('event', 'EventController');
	Route::resource('user', 'UserController');
});

Route::get('/', function() {
	$upcoming_events = \App\Event::upcoming()->get();
	$ongoing_events = \App\Event::ongoing()->get();

	return view('front/index',
		compact(
			'upcoming_events',
			'ongoing_events'
		)
	);
});

Route::resource('event', 'EventController');

app/Server.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Service;

class Server extends Model
{
	/**
	 * The attributes available for mass assignment.
	 *
	 * @var array
	 **/
	protected $fillable = [
		'address',
		'hostname',
		'name',
	];

	/**
	 * A Server has Many Services
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function services()
	{
		return $this->hasMany(Service::class);
	}

	/**
	 * Ping the server to see if it is up. If ICMP is disabled this will fail to ascertain the status.
	 *
	 * @return boolean
	 */
	public function ping()
	{
		$output = [];
		exec('ping -c 1 ' . $this->address, $output);

		if (!isset($output[4])) {
			return false;
		}

		if (strpos($output[4], '100% packet loss') !== false) {
			return false;
		}
		
		return true;
	}
}

app/Http/Controllers/Admin/ServerController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Server;

class ServerController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$servers = Server::all();

		return view('admin/server/index', compact('servers'));
	}

	/**
	 * Display a template for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('admin/server/create');
	}

	/**
	 * Display a template for editing an existing resource.
	 *
	 * @return Response
	 */
	public function edit($server)
	{
		$server = Server::findOrFail($server);
		$services = $server->services;

		return view('admin/server/edit',
			compact(
				'server',
				'services'
			)
		);
	}

	/**
	 * Create a new resource.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$input = $request->input();

		Server::create($input);

		return redirect()->route('admin.server.index');
	}

	/**
	 * Update an existing resource.
	 *
	 * @return Response
	 */
	public function update($server, Request $request)
	{
		$server = Server::findOrFail($server);
		$input = $request->input();

		$server->update($input);

		return redirect()->back();
	}

	/**
	 * Delete an existing resource
	 *
	 * @return Response
	 */
	public function destroy($server)
	{
		Server::destroy($servr);

		return redirect()->back();
	}
}

resources/views/admin/server/create.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Servers</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			{!! Form::open(['route' => 'admin.server.store', 'method' => 'POST']) !!}
				<legend>New Server</legend>
				<div class="form-group">
					{!! Form::label('address', 'Address', ['class' => 'control-label']) !!}
					{!! Form::text('address', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('hostname', 'HostName', ['class' => 'control-label']) !!}
					{!! Form::text('hostname', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
					{!! Form::text('name', null, ['class' => 'form-control']) !!}
				</div>

				{!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
			{!! Form::close() !!}
		</div>
	</div>
@stop

resources/views/admin/server/edit.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Servers</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			{!! Form::model($server, ['route' => ['admin.server.update', $server->id], 'method' => 'PUT']) !!}
				<legend>
					Edit Server
					@if ($server->ping())
						<button class="btn btn-xs btn-success">Online</button>
					@else
						<button class="btn btn-xs btn-danger">Offline</button>
					@endif
				</legend>
				<div class="form-group">
					{!! Form::label('address', 'Address', ['class' => 'control-label']) !!}
					{!! Form::text('address', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('hostname', 'HostName', ['class' => 'control-label']) !!}
					{!! Form::text('hostname', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
					{!! Form::text('name', null, ['class' => 'form-control']) !!}
				</div>

				{!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
			{!! Form::close() !!}
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<h2>
				Services
				<a href="{{ route('admin.server.service.create', $server->id) }}" class="btn btn-xs btn-success pull-right">New Service</a>
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-striped table-bordered">
				<thead>
					<th>Type</th>
					<th>Username</th>
					<th>Password</th>
					<th>Port</th>
					<th>URL</th>
					<th>Status</th>
					<th>Actions</th>
				</thead>
				@foreach ($services as $service)
					<tr>
						<td>{{ $service->serviceType->name }}</td>
						<td>{{ $service->username }}</td>
						<td>{{ $service->password }}</td>
						<td>{{ $service->port }}</td>
						<td>{{ $service->url }}</td>
						<td>
							@if ($service->check())
								<button class="btn btn-xs btn-success">Online</button>
							@else
								<button class="btn btn-xs btn-danger">Offline</button>
							@endif
						</td>
						<td>
							<a href="{{ route('admin.server.service.edit', [$server->id, $service->id]) }}" class="btn btn-xs btn-primary">Edit</a>
						</td>
					</tr>
				@endforeach
			</table>
		</div>
	</div>
@stop

resources/views/admin/server/index.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Servers <a href="{{ route('admin.server.create') }}" class="btn btn-success pull-right">New Server</a> </h2>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-striped table-bordered">
				<thead>
					<th>ID</th>
					<th>Address</th>
					<th>HostName</th>
					<th>Name</th>
					<th>Status</th>
					<th>Actions</th>
				</thead>
				<tbody>
					@foreach ($servers as $server)
						<tr>
							<td>{{ $server->id }}</td>
							<td>{{ $server->address }}</td>
							<td>{{ $server->hostname }}</td>
							<td>{{ $server->name }}</td>
							<td>
								@if ($server->ping() == true)
									<button class="btn-xs btn btn-success">Online</button>
								@else
									<button class="btn-xs btn btn-danger">Offline</button>
								@endif
							</td>
							<td>
								<a href="{{ route('admin.server.edit', $server->id) }}" class="btn btn-xs btn-primary">Edit</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@stop