app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function()
{
	Route::resource('server', 'ServerController');
	Route::resource('server.service', 'ServiceController', ['except' => ['index', 'show']]);
	Route::resource('event', 'EventController');
	Route::resource('user', 'UserController');
});

Route::get('/', function() {
	$upcoming_events = \App\Event::upcoming()->get();
	$ongoing_events = \App\Event::ongoing()->get();

	return view('front/index',
		compact(
			'upcoming_events',
			'ongoing_events'
		)
	);
});

Route::resource('event', 'EventController');

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'admin',
        'email',
        'password',
        'username',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/Admin/UserController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$users = User::all();

		return view('admin/user/index', compact('users'));
	}

	/**
	 * Display a template for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('admin/user/create');
	}

	/**
	 * Display a template for editing an existing resource.
	 *
	 * @return Response
	 */
	public function edit($user)
	{
		$user = User::findOrFail($user);

		return view('admin/user/edit')->with(['user' => $user]);
	}

	/**
	 * Create a new resource.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
			'username' => 'required',
			'password' => 'required|confirmed',
			'email'    => 'required|email',
		]);

		$input = $request->input();

		$user = User::create($input);

		return redirect()->route('admin.user.index');
	}

	/**
	 * Update an existing resource.
	 *
	 * @return Response
	 */
	public function update($user, Request $request)
	{
		$this->validate($request, [
			'username' => 'required',
			'password' => 'confirmed',
			'email'    => 'required|email',
		]);

		$input = $request->input();

		$user = User::findOrFail($user);
		$user->update($input);

		return redirect()->route('admin.user.index');
	}

	/**
	 * Delete an existing resource.
	 *
	 * @return Response
	 */
	public function destroy()
	{
		User::destroy($user);

		return redirect()->route('admin.user.index');
	}
}

resources/views/admin/user/create.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Users</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			{!! Form::open(['route' => 'admin.user.store', 'method' => 'POST']) !!}
				<legend>Create User</legend>
				<div class="form-group">
					{!! Form::label('username', 'Username', ['class' => 'control-label']) !!}
					{!! Form::text('username', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
					{!! Form::text('email', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('password', 'Password', ['class' => 'control-label']) !!}
					{!! Form::password('password', ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('password_confirmation', 'Confirm Password', ['class' => 'control-label']) !!}
					{!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('admin', 'Is Admin?', ['class' => 'control-lable']) !!}
					{!! Form::radio('admin', '1', false) !!} Yes
					{!! Form::radio('admin', '0', true) !!} No
				</div>

				{!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
			{!! Form::close() !!}
		</div>
	</div>
@stop

resources/views/admin/user/edit.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>Users</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			{!! Form::model($user, ['route' => ['admin.user.update', $user->id], 'method' => 'PUT']) !!}
				<legend>Edit User</legend>
				<div class="form-group">
					{!! Form::label('username', 'Username', ['class' => 'control-label']) !!}
					{!! Form::text('username', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
					{!! Form::text('email', null, ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('password', 'Password', ['class' => 'control-label']) !!}
					{!! Form::password('password', ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('password_confirmation', 'Confirm Password', ['class' => 'control-label']) !!}
					{!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
				</div>
				<div class="form-group">
					{!! Form::label('admin', 'Is Admin?', ['class' => 'control-lable']) !!}
					{!! Form::radio('admin', '1') !!} Yes
					{!! Form::radio('admin', '0') !!} No
				</div>

				{!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
			{!! Form::close() !!}
		</div>
	</div>
@stop

resources/views/admin/user/index.blade.php
@extends('admin/layout')

@section('content')
	<div class="row">
		<div class="col-lg-12">
			<h2>
				Users
				<a href="{{ route('admin.user.create') }}" class="btn btn-success pull-right">New User</a>
			</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			<table class="table table-striped table-bordered">
				<thead>
					<th>Username</th>
					<th>Email</th>
					<th>Is Admin?</th>
					<th>Actions</th>
				</thead>
				<tbody>
					@foreach ($users as $user)
						<tr>
							<td>{{ $user->username }}</td>
							<td>{{ $user->email }}</td>
							<td>{{ $v = ($user->admin == 1) ? 'Yes' : 'No' }}</td>
							<td>
								<a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-primary btn-xs">Edit</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@stop